# Generated by Django 5.0.6 on 2024-06-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="owner",
            new_name="user",
        ),
    ]
